---
title: "HGF"
author: "Jesper Fischer Ehmsen"
date: '2022-11-01'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```

## R Markdown







```{r}
df = raw %>% filter(id ==552)




df$u = ifelse(df$cue == "low-tone" & df$stim == "TGI", a <- 1-(df$vasResp_1/(df$vasResp_1+df$vasResp_2)),
              ifelse(df$cue == "high-tone" & df$stim == "TGI", a <- (df$vasResp_1/(df$vasResp_1+df$vasResp_2)),
  ifelse(df$cue == "low-tone" & df$stim == "cold", a <- 0, 
       ifelse(df$cue == "high-tone" & df$stim == "warm", a <- 0,
              ifelse(df$cue == "low-tone" & df$stim == "warm", a <- 1,
                     ifelse(df$cue == "high-tone" & df$stim == "cold", a <- 1, a <- 0.1))))))

df$predResp2 = ifelse(df$cue == "low-tone" & df$predResp == "cold", a <- 0, 
       ifelse(df$cue == "high-tone" & df$predResp == "warm", a <- 0,
              ifelse(df$cue == "low-tone" & df$predResp == "warm", a <- 1,
                     ifelse(df$cue == "high-tone" & df$predResp == "cold", a <- 1, a <- NaN))))











```


